---
- name: filebrowser
  hosts: "all"
  become: yes

  tasks:
  - name: Create filebrowser directory 
    file:
      path: /home/rocky/filebrowser
      state: directory
      owner: rocky
      group: rocky
      mode: '1777'

  - name: Create filebrowser directory 
    file:
      path: /home/rocky/filebrowser-db
      state: directory
      owner: rocky
      group: rocky
      mode: '1777'

  - name: Touch a file and set permissions to 0644
    ansible.builtin.file:
      path: "/home/rocky/filebrowser-db/filebrowser.db"
      state: touch
      owner: rocky
      group: rocky
      mode: '0666'

  - name: setup filebrowser container
    containers.podman.podman_container:
      name: filebrowser
      image: docker.io/filebrowser/filebrowser:s6
      state: started
      volumes:
      - /home/rocky/filebrowser/:/srv:z
      - /home/rocky/filebrowser-db/filebrowser.db:/database/filebrowser.db:z
      ports:
      - "8080:80"
      env:
          PUID: "0"
          PGID: "0"

